import { aliases, key, names, quote, slug, specs, takes } from "./util.js";
//#region lib/api/src/cli/completion/bash.ts
/**
* A bash script with the tree baked in. Targets bash 3.2 (what macOS ships), so no
* associative arrays, no `mapfile`, and every `compopt` guarded.
*
* @example bash(Table.of(root), 'app') // '# app completion for bash…'
*/
var bash = (entries, options) => {
	const { name, invoke } = options;
	const fn = `_${slug(name)}`;
	return [
		`# ${name} completion for bash. Generated by \`${name} completion bash\`.`,
		``,
		`${fn}_table() {`,
		`  cmds=''; flags=''; takes=''; slots=0; variadic=''`,
		`  case "$1" in`,
		...entries.map((entry) => `    ${quote(key(entry.path))}) ${assign(entry)} ;;`),
		`  esac`,
		`}`,
		``,
		`${fn}_spec() {`,
		`  spec=''; mode=''`,
		...block(entries),
		`}`,
		``,
		...norm(fn, entries),
		...invoke ? [
			`${fn}_cmd=(${invoke.map(quote).join(" ")})`,
			``,
			call(fn),
			``
		] : [],
		driver(fn, invoke !== void 0),
		``,
		`complete -o default -F ${fn} ${quote(name)}`,
		``
	].join("\n");
};
var assign = (entry) => {
	const parts = [`cmds=${quote(entry.commands.map((item) => item.value).join(" "))}`, `flags=${quote(names(entry).join(" "))}`];
	if (takes(entry).length > 0) parts.push(`takes=${quote(takes(entry).join(" "))}`);
	if (entry.positionals.length > 0) parts.push(`slots=${entry.positionals.length}`);
	if (entry.variadic) parts.push(`variadic=1`);
	return parts.join("; ");
};
var block = (entries) => {
	const cases = entries.flatMap((entry) => specs(entry).map(([keys, spec]) => {
		return `    ${keys.map((k) => quote(`${key(entry.path)}|${k}`)).join("|")}) ${typeof spec === "string" ? `mode=${quote(spec)}` : `spec=${quote(spec.join(" "))}`} ;;`;
	}));
	return cases.length === 0 ? [] : [
		`  case "$1|$2" in`,
		...cases,
		`  esac`
	];
};
/** `find` accepts a camelCase name as well as its kebab form; the table only holds kebab. */
var norm = (fn, entries) => {
	const pairs = aliases(entries);
	const body = pairs.length === 0 ? [`  norm="$1"`] : [
		`  norm="$1"`,
		`  case "$1" in`,
		...pairs.map(([from, to]) => `    ${quote(from)}) norm=${quote(to)} ;;`),
		`  esac`
	];
	return [
		`${fn}_norm() {`,
		...body,
		`}`,
		``
	];
};
/** Fills `spec` and `mode`, so the emit below is the same on both paths. */
var call = (fn) => `${fn}_call() {
  local line value
  local -a out
  spec=''; mode='default'

  # Process substitution, not a pipe: a pipe runs the loop in a subshell and \`out\` would
  # not survive it. \`mapfile\` is bash 4, so this stays a read loop.
  while IFS= read -r line; do
    case "$line" in
      :*) mode="\${line#:}"; continue ;;
    esac

    # bash cannot show descriptions, and \`compgen -W\` word-splits, so both are dropped.
    value="\${line%%$'\\t'*}"
    [[ -z "$value" ]] && continue
    case "$value" in *[[:space:]]*) continue ;; esac
    out[\${#out[@]}]="$value"
  done < <( "\${${fn}_cmd[@]}" __complete -- "$@" 2>/dev/null )

  spec="\${out[*]}"
  return 0
}`;
var driver = (fn, dynamic) => {
	const track = dynamic ? `
    [[ "$w" == '--' ]] && terminated=1
    [[ "$w" == -[!-]?* ]] && dirty=1` : "";
	const escape = dynamic ? `
  escape=''
  [[ -n "$dirty$terminated" ]] && escape=1
  [[ "$cur" == -* && "$cur" == *=* ]] && escape=1
  [[ "$cur" == --no* ]] && escape=1
  [[ "$cur" == -[!-]?* ]] && escape=1
` : "";
	const branch = dynamic ? `  if [[ -n "$escape" ]]; then\n    ${fn}_call "\${cw[@]}"\n  el` : "  ";
	const redo = dynamic ? `\n    [[ "$mode" == call ]] && ${fn}_call "\${cw[@]}"` : "";
	return `${fn}() {
  local cur w path pending i n slot head norm
  local cmds flags takes slots variadic spec mode${dynamic ? " dirty terminated escape" : ""}
  local -a cw

  # bash splits words on '=' and ':' (COMP_WORDBREAKS); rejoin so the table matches.
  for (( i = 1; i <= COMP_CWORD; i++ )); do
    w="\${COMP_WORDS[i]}"
    n=\${#cw[@]}
    if (( n > 0 )) && [[ "$w" == [=:] || "\${cw[n-1]}" == *[=:] ]]; then
      cw[n-1]="\${cw[n-1]}$w"
    else
      cw[n]="$w"
    fi
  done
  (( \${#cw[@]} == 0 )) && cw[0]=''

  cur="\${cw[\${#cw[@]}-1]}"
  path=''; pending=''; slot=0

  for (( i = 0; i < \${#cw[@]} - 1; i++ )); do
    w="\${cw[i]}"
    if [[ -n "$pending" ]]; then pending=''; continue; fi${track}
    ${fn}_table "$path"
    if [[ "$w" == -* ]]; then
      [[ " $takes " == *" $w "* ]] && pending="$w"
    elif ${fn}_norm "$w"; [[ " $cmds " == *" $norm "* ]]; then
      path="\${path:+$path }$norm"; slot=0
    else
      slot=$(( slot + 1 ))
    fi
  done

  COMPREPLY=()
  ${fn}_table "$path"
${escape}
${branch}if [[ -n "$pending" ]]; then
    ${fn}_spec "$path" "$pending"${redo}
  elif [[ "$cur" == -* ]]; then
    # \`--flag=value\` is not split here; an empty reply lets \`-o default\` take it.
    [[ "$cur" == *=* ]] && return 0
    spec="$flags"
  else
    # Once a positional is taken, \`find\` has already failed — no subcommand can follow.
    head=''; (( slot == 0 )) && head="$cmds"
    [[ -n "$variadic" ]] && (( slot >= slots )) && slot=$(( slots - 1 ))
    ${fn}_spec "$path" "@$slot"${redo}
    spec="$head $spec"
  fi

  if [[ "$mode" == dir ]]; then
    COMPREPLY=( $(compgen -d -- "$cur") )
  elif [[ -n "\${spec// /}" ]]; then
    COMPREPLY=( $(compgen -W "$spec" -- "$cur") )
  fi

  # bash-completion only; without it a candidate containing ':' completes twice over.
  type __ltrim_colon_completions >/dev/null 2>&1 && __ltrim_colon_completions "$cur"
  return 0
}`;
};
//#endregion
export { bash };

//# sourceMappingURL=bash.js.map