import { aliases, escape, key, slug, specs, takes } from "./util.js";
//#region lib/api/src/cli/completion/fish.ts
/**
* A fish script with the tree baked in. fish consumes `value\ttab` natively, so it
* gets the richest output of the three.
*
* @example fish(Table.of(root), 'app') // '# app completion for fish…'
*/
var fish = (entries, options) => {
	const { name, invoke } = options;
	const fn = `__${slug(name)}`;
	return [
		`# ${name} completion for fish. Generated by \`${name} completion fish\`.`,
		``,
		lookup(`${fn}_cmds`, entries, (entry) => entry.commands.map((item) => item.value).join(" ")),
		``,
		lookup(`${fn}_takes`, entries, (entry) => takes(entry).join(" ")),
		``,
		lookup(`${fn}_slots`, entries, (entry) => `${entry.positionals.length} ${entry.variadic ? 1 : 0}`, "0 0"),
		``,
		items(`${fn}_items`, entries),
		``,
		norm(`${fn}_norm`, entries),
		``,
		...invoke ? [`set -g ${fn}_cmd ${invoke.map(escape).join(" ")}`, ``] : [],
		driver(fn, invoke !== void 0),
		``,
		`complete -c ${escape(name)} -f -a '(${fn}_complete)'`,
		``
	].join("\n");
};
/** Paths are keyed with a leading `/` so the root is not an empty `case` pattern. */
var lookup = (fn, entries, value, fallback) => {
	const cases = entries.map((entry) => [entry, value(entry)]).filter(([, text]) => text.trim().length > 0).map(([entry, text]) => `    case ${escape(`/${key(entry.path)}`)}\n      echo ${escape(text)}`);
	return [
		`function ${fn} -a path`,
		`  switch "/$path"`,
		...cases,
		...fallback ? [`    case '*'`, `      echo ${escape(fallback)}`] : [],
		`  end`,
		`end`
	].join("\n");
};
/** `find` accepts a camelCase name as well as its kebab form; the table only holds kebab. */
var norm = (fn, entries) => [
	`function ${fn} -a name`,
	`  switch "$name"`,
	...aliases(entries).flatMap(([from, to]) => [`    case ${escape(from)}`, `      echo ${escape(to)}`]),
	`    case '*'`,
	`      echo "$name"`,
	`  end`,
	`end`
].join("\n");
var items = (fn, entries) => {
	const cases = [];
	for (const entry of entries) {
		const at = (keys) => keys.map((k) => escape(`/${key(entry.path)}|${k}`)).join(" ");
		const flags = entry.flags.flatMap((flag) => flag.names.map((value) => ({
			value,
			description: flag.description
		})));
		for (const [keys, list] of [[["@cmds"], entry.commands], [["@flags"], flags]]) if (list.length > 0) cases.push(`    case ${at([...keys])}\n${print([...list])}`);
		for (const [keys, spec] of specs(entry)) {
			const body = typeof spec === "string" ? `      echo ${escape(`:${spec}`)}` : print(spec.map((value) => ({ value })));
			cases.push(`    case ${at(keys)}\n${body}`);
		}
	}
	return [
		`function ${fn} -a path -a key`,
		`  switch "/$path|$key"`,
		...cases,
		`  end`,
		`end`
	].join("\n");
};
/** `printf` expands the escapes in its format, which single quotes would not. */
var print = (list) => {
	const described = list.filter((item) => item.description);
	const plain = list.filter((item) => !item.description);
	const lines = [];
	const args = (values) => values.map(escape).join(" ");
	if (described.length > 0) lines.push(`      printf '%s\\t%s\\n' ${args(described.flatMap((i) => [i.value, i.description ?? ""]))}`);
	if (plain.length > 0) lines.push(`      printf '%s\\n' ${args(plain.map((item) => item.value))}`);
	return lines.join("\n");
};
var driver = (fn, dynamic) => {
	const call = dynamic ? `
# Prints the callback's candidates, then acts on its trailing directive.
function ${fn}_call
  set -l shown 0
  set -l mode default

  for line in ($${fn}_cmd __complete -- $argv 2>/dev/null)
    if string match -q -- ':*' $line
      set mode (string sub -s 2 -- $line)
    else
      echo $line
      set shown 1
    end
  end

  set -l cur (commandline -ct)
  switch $mode
    case file
      __fish_complete_path "$cur"
    case dir
      __fish_complete_directories "$cur"
    case default
      test $shown -eq 0; and __fish_complete_path "$cur"
  end
end
` : "";
	const track = dynamic ? `
    test "$t" = '--'; and set terminated 1
    string match -qr -- '^-[^-].' $t; and set dirty 1` : "";
	const escape = dynamic ? `
  if test -n "$dirty$terminated"
    or string match -qr -- '^-.*=' -- $cur
    or string match -q -- '--no*' -- $cur
    or string match -qr -- '^-[^-].' -- $cur
    ${fn}_call $tokens "$cur"
    return
  end
` : "";
	const redo = dynamic ? `
    if test "$mode" -eq 2
      ${fn}_call $tokens "$cur"
      return
    end` : "";
	return `${call}# Returns non-zero when the key declared nothing, so the caller can fall back.
function ${fn}_values -a path -a key -a cur
  set -l out (${fn}_items "$path" "$key")
  test (count $out) -eq 0; and return 1
  switch $out[1]
    case ':file'
      __fish_complete_path "$cur"
    case ':dir'
      __fish_complete_directories "$cur"
    case ':call'
      return 2
    case '*'
      printf '%s\\n' $out
  end
end

function ${fn}_complete
  set -l tokens (commandline -opc)
  test (count $tokens) -gt 0; and set -e tokens[1]
  set -l cur (commandline -ct)
  set -l path ''
  set -l pending ''
  set -l slot 0
  set -l dirty ''
  set -l terminated ''

  for t in $tokens
    if test -n "$pending"
      set pending ''
      continue
    end${track}
    if string match -q -- '-*' $t
      if contains -- $t (${fn}_takes "$path" | string split -n ' ')
        set pending $t
      end
      continue
    end
    set -l n (${fn}_norm $t)
    if contains -- $n (${fn}_cmds "$path" | string split -n ' ')
      test -z "$path"; and set path $n; or set path "$path $n"
      set slot 0
    else
      set slot (math $slot + 1)
    end
  end
${escape}
  if test -n "$pending"
    ${fn}_values "$path" "$pending" "$cur"
    set -l mode $status${redo}
    test "$mode" -eq 1; and __fish_complete_path "$cur"
    return
  end

  if string match -q -- '-*' $cur
    ${fn}_items "$path" '@flags'
    return
  end

  # Once a positional is taken, \`find\` has already failed — no subcommand can follow.
  set -l head $slot
  set -l info (${fn}_slots "$path" | string split ' ')
  if test "$info[2]" = 1 -a "$slot" -ge "$info[1]"
    set slot (math "$info[1]" - 1)
  end

  set -l cmds
  test "$head" -eq 0; and set cmds (${fn}_items "$path" '@cmds')
  test (count $cmds) -gt 0; and printf '%s\\n' $cmds

  ${fn}_values "$path" "@$slot" "$cur"
  set -l mode $status${redo}
  # Only fall back to paths when nothing else matched, as \`-o default\` and \`_default\` do.
  test "$mode" -eq 1 -a (count $cmds) -eq 0; and __fish_complete_path "$cur"
end`;
};
//#endregion
export { fish };

//# sourceMappingURL=fish.js.map