import { aliases, key, quote, slug, specs, takes } from "./util.js";
//#region lib/api/src/cli/completion/zsh.ts
/**
* A zsh script with the tree baked in. zsh keeps `--flag=value` as one word and has
* real arrays, so descriptions survive here where bash drops them.
*
* @example zsh(Table.of(root), 'app') // '#compdef app…'
*/
var zsh = (entries, options) => {
	const { name, invoke } = options;
	const fn = `_${slug(name)}`;
	return [
		`#compdef ${name}`,
		`# Generated by \`${name} completion zsh\`.`,
		``,
		`${fn}_table() {`,
		`  cmdv=(); cmdd=(); flagv=(); flagd=(); takes=''; slots=0; variadic=''`,
		`  case "$1" in`,
		...entries.flatMap((entry) => [
			`    (${quote(key(entry.path))})`,
			...assign(entry),
			`      ;;`
		]),
		`  esac`,
		`}`,
		``,
		`${fn}_spec() {`,
		`  spec=''; mode=''`,
		...block(entries),
		`}`,
		``,
		...norm(fn, entries),
		...invoke ? [
			`${fn}_cmd=(${invoke.map(quote).join(" ")})`,
			``,
			call(fn),
			``
		] : [],
		driver(fn, invoke !== void 0),
		``,
		`if [ "$funcstack[1]" = "${fn}" ]; then`,
		`  ${fn} "$@"`,
		`else`,
		`  compdef ${fn} ${quote(name)}`,
		`fi`,
		``
	].join("\n");
};
var assign = (entry) => {
	const lines = [];
	const list = (values) => values.map(quote).join(" ");
	if (entry.commands.length > 0) {
		lines.push(`      cmdv=(${list(entry.commands.map((item) => item.value))})`);
		lines.push(`      cmdd=(${list(entry.commands.map((item) => item.description ?? ""))})`);
	}
	lines.push(`      flagv=(${list(entry.flags.flatMap((flag) => flag.names))})`);
	lines.push(`      flagd=(${list(entry.flags.flatMap((flag) => flag.names.map(() => flag.description ?? "")))})`);
	if (takes(entry).length > 0) lines.push(`      takes=${quote(takes(entry).join(" "))}`);
	if (entry.positionals.length > 0) lines.push(`      slots=${entry.positionals.length}`);
	if (entry.variadic) lines.push(`      variadic=1`);
	return lines;
};
var block = (entries) => {
	const cases = entries.flatMap((entry) => specs(entry).map(([keys, spec]) => {
		return `    (${keys.map((k) => quote(`${key(entry.path)}|${k}`)).join("|")}) ${typeof spec === "string" ? `mode=${quote(spec)}` : `spec=${quote(spec.join(" "))}`} ;;`;
	}));
	return cases.length === 0 ? [] : [
		`  case "$1|$2" in`,
		...cases,
		`  esac`
	];
};
/** `find` accepts a camelCase name as well as its kebab form; the table only holds kebab. */
var norm = (fn, entries) => {
	const pairs = aliases(entries);
	const body = pairs.length === 0 ? [`  norm="$1"`] : [
		`  norm="$1"`,
		`  case "$1" in`,
		...pairs.map(([from, to]) => `    (${quote(from)}) norm=${quote(to)} ;;`),
		`  esac`
	];
	return [
		`${fn}_norm() {`,
		...body,
		`}`,
		``
	];
};
/** Appends to `outv`/`outd`, so the `compadd` tail below is shared with the static path. */
var call = (fn) => `${fn}_call() {
  local line
  mode='default'

  for line in \${(f)"$(${fn}_cmd_run "$@")"}; do
    [[ -z "$line" ]] && continue
    if [[ "$line" == :* ]]; then mode="\${line#:}"; continue; fi
    outv+=("\${line%%$'\t'*}")
    # An untabbed line stays itself, so the two arrays never fall out of step.
    outd+=("\${line/$'\t'/ -- }")
  done
}

${fn}_cmd_run() {
  "\${${fn}_cmd[@]}" __complete -- "$@" 2>/dev/null
}`;
var driver = (fn, dynamic) => {
	const track = dynamic ? `
    [[ "$w" == '--' ]] && terminated=1
    [[ "$w" == -[^-]?* ]] && dirty=1` : "";
	const escape = dynamic ? `
  escape=''
  [[ -n "$dirty$terminated" ]] && escape=1
  [[ "$cur" == -* && "$cur" == *=* ]] && escape=1
  [[ "$cur" == --no* ]] && escape=1
  [[ "$cur" == -[^-]?* ]] && escape=1
` : "";
	const branch = dynamic ? `  if [[ -n "$escape" ]]; then\n    ${fn}_call "\${cw[@]}"\n  el` : "  ";
	const redo = dynamic ? `\n    if [[ "$mode" == call ]]; then ${fn}_call "\${cw[@]}"; else` : "\n    if true; then";
	return `${fn}() {
  # \`at\` not \`path\`: zsh ties \`path\` to \`PATH\`, and a local blanks it for the callback.
  local cur w at pending i slot head norm
  local takes slots variadic spec mode${dynamic ? " dirty terminated escape" : ""}
  local -a cw cmdv cmdd flagv flagd outv outd

  cw=("\${(@)words[2,CURRENT]}")
  (( \${#cw} == 0 )) && cw=('')
  cur="\${cw[-1]}"
  at=''; pending=''; slot=0

  for (( i = 1; i < \${#cw}; i++ )); do
    w="\${cw[i]}"
    if [[ -n "$pending" ]]; then pending=''; continue; fi${track}
    ${fn}_table "$at"
    if [[ "$w" == -* ]]; then
      [[ " $takes " == *" $w "* ]] && pending="$w"
    elif ${fn}_norm "$w"; (( \${cmdv[(Ie)$norm]} )); then
      at="\${at:+$at }$norm"; slot=0
    else
      (( slot++ ))
    fi
  done

  ${fn}_table "$at"
${escape}
${branch}if [[ -n "$pending" ]]; then
    ${fn}_spec "$at" "$pending"${redo}
      for w in \${=spec}; do outv+=("$w"); outd+=("$w"); done
    fi
  elif [[ "$cur" == -* ]]; then
    for (( i = 1; i <= \${#flagv}; i++ )); do
      outv+=("\${flagv[i]}")
      outd+=("\${flagv[i]}\${flagd[i]:+ -- \${flagd[i]}}")
    done
  else
    # Once a positional is taken, \`find\` has already failed — no subcommand can follow.
    head=$(( slot == 0 ))
    [[ -n "$variadic" ]] && (( slot >= slots )) && slot=$(( slots - 1 ))
    ${fn}_spec "$at" "@$slot"
    (( head )) && for (( i = 1; i <= \${#cmdv}; i++ )); do
      outv+=("\${cmdv[i]}")
      outd+=("\${cmdv[i]}\${cmdd[i]:+ -- \${cmdd[i]}}")
    done${redo}
      for w in \${=spec}; do outv+=("$w"); outd+=("$w"); done
    fi
  fi

  if [[ "$mode" == dir ]]; then
    _files -/
  elif [[ "$mode" == file ]]; then
    _files
  elif (( \${#outv} )); then
    # \`-Q\` because the values are already the exact text to insert; \`_describe\` is
    # avoided because it splits on ':' and descriptions carry '(default: 3)'.
    compadd -Q -d outd -a outv
  else
    _default
  fi
}`;
};
//#endregion
export { zsh };

//# sourceMappingURL=zsh.js.map