Object.defineProperty(exports, Symbol.toStringTag, { value: "Module" });
const require_run = require("./core/run.cjs");
require("./core/index.cjs");
const require_build = require("./build.cjs");
exports.choice = require_build.choice;
exports.cmd = require_build.cmd;
exports.flag = require_build.flag;
exports.list = require_build.list;
exports.num = require_build.num;
exports.optional = require_build.optional;
exports.run = require_run.run;
exports.string = require_build.string;
