Object.defineProperty(exports, Symbol.toStringTag, { value: "Module" });
const require_runtime = require("../../_virtual/_rolldown/runtime.cjs");
const require_vite = require("../_util/vite.cjs");
const require_shared = require("../_util/shared.cjs");
const require_file = require("../_util/file.cjs");
let node_path = require("node:path");
node_path = require_runtime.__toESM(node_path, 1);
//#region lib/vite/src/virtual/plugin.ts
var NS = require_vite.namespace("virtual", { manifest: "@pingid/lib/vite/manifest" });
var virtual = (modules, options = {}) => {
	const pkg = options.pkg ?? "@pingid/lib/vite";
	const style = options.style ?? "manifest";
	const mods = new Map(Object.entries(modules).map(([key, input]) => {
		const it = typeof input === "string" ? {
			file: input,
			exports: void 0
		} : input;
		return [key, {
			...it,
			key,
			file: node_path.default.resolve(it.file)
		}];
	}));
	return {
		name: "pingid:virtual",
		enforce: "pre",
		config: () => ({
			optimizeDeps: { exclude: [pkg] },
			ssr: { noExternal: [pkg] },
			resolve: { alias: { "@pingid/lib/vite/virtual/runtime": require_file.File.project({}, "./runtime.ts").path } }
		}),
		configResolved: async (config_) => {
			if (options.types === false) return;
			const file = require_file.File.for(config_.root, options.types ?? "src/virtual.d.ts");
			await file.write(build_decls(style, [...mods.values()], file.dir));
		},
		resolveId: {
			order: "pre",
			handler(id) {
				return NS.match(id, (m) => {
					if (m.kind === "manifest") {
						if (style === "manifest") return m.encoded;
						return this.error(`"@pingid/lib/vite/virtual" needs the manifest, which is only emitted with \`style: 'manifest'\` — under \`style: 'module'\` import a key directly, e.g. \`import { register } from "${NS.unknown([...mods.keys()][0] ?? "key").id}"\``);
					}
					if (mods.has(m.name)) return m.encoded;
					return this.error(`unknown virtual module "${m.name}" — known keys: ${[...mods.keys()].join(", ") || "(none)"}`);
				});
			}
		},
		async load(id) {
			return NS.match(id, async (m) => {
				if (m.kind === "manifest") return build_manifest([...mods.values()]);
				const mod = mods.get(m.name);
				return mod ? build_wrapper(mod) : null;
			});
		}
	};
};
var build_manifest = (mods) => {
	const w = require_shared.Jitt.create();
	w.ln("export const mods =");
	w.fields((f) => {
		mods.forEach((m) => {
			f(m.key, () => {
				w.fields((f) => {
					f("exports", m.exports ? `[${m.exports.map(require_shared.Jitt.str).join(", ")}]` : "null");
					f("load", `() => import(${require_shared.Jitt.str(NS.unknown(m.key).id)})`);
				});
			});
		});
	});
	return w.toString();
};
var build_wrapper = (m) => {
	const spec = require_shared.Jitt.str(m.file.replaceAll("\\", "/"));
	const w = require_shared.Jitt.create();
	w.ln("import { create } from '@pingid/lib/vite/virtual/runtime'");
	if (m.exports) {
		w.ln(`import { ${m.exports.join(", ")} } from ${spec}`);
		w.ln(`const mod = { ${m.exports.join(", ")} }`);
		w.ln("export { mod }");
	} else w.ln(`import * as mod from ${spec}`, "export { mod }");
	w.ln("const { register, accept } = create(mod, import.meta?.hot)");
	w.ln("export { register }");
	w.ln("if (import.meta.hot)");
	w.block(() => {
		w.ln("import.meta.hot.accept((newModule) =>");
		w.block(() => {
			w.ln(`newModule && accept(newModule)`);
		});
		w.ln(")");
	});
	return w.toString();
};
var build_decls = (style, mods, dir) => {
	const w = require_shared.Jitt.create();
	w.ln("// Generated by @pingid/lib/vite. Do not edit.");
	if (style === "manifest") {
		w.ln("declare module '@pingid/lib/vite/types'");
		w.block(() => {
			w.ln("export interface VirtualModule");
			w.block(() => mods.forEach((m) => w.ln(`${require_shared.Jitt.str(m.key)}: ${modType(m, dir)}`)));
		});
	} else mods.forEach((m) => {
		w.ln(`declare module ${require_shared.Jitt.str(NS.unknown(m.key).id)}`);
		w.block(() => {
			w.ln(`export type Mod = ${modType(m, dir)}`);
			w.ln("export const mod: Mod");
			w.ln("export const register: (cb: (mod: Mod) => (() => void) | void) => () => void");
		});
	});
	return `${w.toString()}\n`;
};
var modType = (mod, dir) => {
	const rel = node_path.default.relative(dir, mod.file).replaceAll("\\", "/").replace(/\.[mc]?tsx?$/, "");
	const t = `typeof import(${require_shared.Jitt.str(rel.startsWith(".") ? rel : `./${rel}`)})`;
	return mod.exports ? `Pick<${t}, ${mod.exports.map(require_shared.Jitt.str).join(" | ")}>` : t;
};
//#endregion
exports.virtual = virtual;

//# sourceMappingURL=plugin.cjs.map